dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - redis-server

addons:
  postgresql: "9.5"
  apt:
    packages:
      - net-tools
      - libpcre3-dev
      - build-essential

services:
  - redis
  - docker

env:
  global:
    - LUAROCKS=3.1.3
    - OPENSSL=1.1.1c
    - CASSANDRA_BASE=2.2.12
    - OPENRESTY_BASE=1.15.8.1
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache
    - BUSTED_ARGS="-o gtest -v --exclude-tags=flaky,ipv6"
    - PLUGIN_NAME=prometheus
    - KONG_TEST_PLUGINS=bundled,$PLUGIN_NAME
    - KONG_PLUGINS=bundled,$PLUGIN_NAME

  matrix:
    - OPENRESTY=$OPENRESTY_BASE
      CASSANDRA=$CASSANDRA_BASE

before_install:
  - git clone https://$GITHUB_TOKEN:@github.com/Kong/kong-ci.git
  - source kong-ci/setup_env.sh
  - git clone --single-branch -b next https://github.com/Kong/kong.git kong-ce

install:
  - luarocks make
  - cd kong-ce
  - make dev
  - cp -r ../spec/fixtures/prometheus spec/fixtures/
  - createuser --createdb kong
  - createdb -U kong kong_tests

script:
  - bin/busted $BUSTED_ARGS ../spec

cache:
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
    - $HOME/.ccm/repository

