dist: bionic

jobs:
  include:
  - name: Kong CE 2.1.x
    env: KONG_VERSION=2.1.x
  - name: Kong CE 2.2.x
    env: KONG_VERSION=2.2.x
  - name: Kong CE 2.3.x
    env: KONG_VERSION=2.3.x
  - name: Kong CE Master
    env: KONG_VERSION=nightly
  # - name: Kong EE 1.5.0.x     # FT to look into failure
  # env: KONG_VERSION=1.5.0.x
  - name: Kong EE 2.4.1.x
    env: KONG_VERSION=2.4.1.x
  - name: Kong Enterprise nightly
    env: KONG_VERSION=nightly-ee

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: HiNnqUzWUG9RFfxSrjb2K9Vzi3ZdTUZYO7Zvjb+lJwP/pwA68RcHpmEvhBa3cMhBokl15w506Mcp8xm/Uj+HUV8HzZEigJ0d2tc7XRVix+gVh4L0wyATHvZ3+GOW3le1CQVVEKLGaanl/lObN0dCP12h4uVyObQRpHEjTf6KtyhW2Atvs5iqOFpfeT/u2oPV9aQ/VRsGjA/72VfVfwggX6KeTLw5+xSDxG7GSt2mGOzmLreOzbaEEeg7FKnN00bMoY/T9lNhNttEQ44VauddSWzOmtCfpR35O1ruIyX5HxOPDt+FD+wMikWtomGm0solOlEEKhlmEi7noTCNb4VW2nhjCEw1O8uQr2Y0MUOPdVQ7/d1FoS4l91X87+/qWAKZzfCnEQfXmM/tSC5OTWGzeRCGAuQKvOuBy9yXuQ2PqedugK+SIgB39CuX5uSwVo23MxNtXDO5c7pAAQQ7MqWjmRSNW92Qp/lKRBIHgfVXgpr4FG6fa9MTnXNB/VGLV7e3QN5evtZQ7c0bwnW+T6Npren2U9IWgkc1dlo/UqBreC3hKVnRf5C+U9RLKM9z6dOiDvLSpS/RF6fl1d9j7UxRsrqP2WCzAHX9rXQtRqEUHtY1x1fZXu2EXdo5Y5zYEtgWMbm6Rh+NzcLy+NKC6bBz/bakhTFto/MeRrkV/vaW+rQ=
